### ISSUE TITLE
Build errors due to updates to Rust

### ISSUE THREAD

**Issue by thecoshman** [servo/rust-glx#4]
The following is preventing builds. I am not sure what it does or what it is used for, though I will get out the books and see if I can't work it out

/src/lib.rs:15:12: 15:17 error: feature has been removed
/src/lib.rs:15 #![feature(phase)]

**Comment by jdm** [comment]
This is dealt with by the https://github.com/servo/rust-glx/tree/rustup_20150109 branch. It will be merged to master when Servo finishes upgrading all of its code.
